<?php
namespace Jimb\RestFilter\Test;

use Jimb\RestFilter\CommonTransformer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-07 at 08:03:47.
 */
class CommonTransformerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var CommonTransformer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CommonTransformer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     *
     * @covers       Jimb\RestFilter\CommonTransformer::requiteFilter
     * @todo   Implement testRequiteFilter().
     */
    public function testRequiteFilterNotPar()
    {
        //测试无值的
        unset($_REQUEST[$this->object->getFiledName()]);
        $this->assertEquals($this->object->RequiteFilter(), false);

    }

    /**
     *
     * @dataProvider addRequiteFilterData
     * @covers       Jimb\RestFilter\CommonTransformer::requiteFilter
     * @todo   Implement testRequiteFilter().
     */
    public function testRequiteFilter($inserPar, $eq = "")
    {
        //测试有值的
        $_REQUEST[$this->object->getFiledName()] = $inserPar;
        $this->assertEquals($this->object->RequiteFilter(), $eq);

    }

    /**
     * @return array
     */
    public function addRequiteFilterData()
    {
        return [
            '< id,name,myinfo.car >' => ['id,name,myinfo.car', ['id' => '0', 'name' => '1', 'myinfo.car' => '2',]],
            '< id >' => ['id', ['id' => '0',]],
            '< 字段值为空 >' => ['', false],
        ];
    }

    /**
     *
     * @dataProvider addGetTransformArrData
     * @covers       Jimb\RestFilter\CommonTransformer::getTransformArr
     * @todo   Implement testGetTransformArr().
     */
    public function testGetTransformArr($inserPar, $eq = "")
    {

        // 新建一个全局管理类
        // 总体测试
        $_REQUEST[$this->object->getFiledName()] = $inserPar;

        $fractal = new \League\Fractal\Manager();
        $resource = new \League\Fractal\Resource\Collection($this->getData(),$this->object);


        $this->assertEquals($fractal->createData($resource)->toJson(), $eq);
    }


    /**
     * @return array
     */
    public function addGetTransformArrData()
    {
        return [
            '< id,name >' => ['id,name', '{"data":[{"id":"1","name":"jianbin"},{"id":"2","name":"jimb55"},{"id":"3","name":"tt"}]}'],
            '< id  >' => ['id', '{"data":[{"id":"1"},{"id":"2"},{"id":"3"}]}'],
            '< id,name,myinfo.car >' => ['id,name,myinfo.car', '{"data":[{"id":"1","name":"jianbin"},{"id":"2","name":"jimb55","myinfo":{"car":{"id":123,"name":"this is a car","yic":{"name":"de"}}}},{"id":"3","name":"tt","myinfo":null}]}'],
            '< id,name,myinfo.car.yic >' => ['id,name,myinfo.car.yic', '{"data":[{"id":"1","name":"jianbin"},{"id":"2","name":"jimb55","myinfo":{"car":{"yic":{"name":"de"}}}},{"id":"3","name":"tt","myinfo":null}]}'],
            '< id,name,myinfo.car.Notyic >' => ['id,name,myinfo.car.Notyic', '{"data":[{"id":"1","name":"jianbin"},{"id":"2","name":"jimb55","myinfo":{"car":null}},{"id":"3","name":"tt","myinfo":null}]}'],
            '< 空 >' => ['', '{"data":[{"id":"1","name":"jianbin","jgdaima":"WBERBKJKJEWR","date":"1998","adresss":"ggz","email":"tangtang@gmail.org"},{"id":"2","name":"jimb55","jgdaima":"FHEWIH3274WENR234NE","date":"1994","adresss":"bbf","email":"Jimb@gmail.org","myinfo":{"name":"jimb55","githubPage":"github:\/\/jimb55","age":"22","like":"i down no","car":{"id":123,"name":"this is a car","yic":{"name":"de"}}}},{"id":"3","name":"tt","jgdaima":"FHEWIH3274WENR234NE","date":"1994","adresss":"ddw","email":"www@gmail.org","myinfo":{"name":"jjjj","githubPage":"hello:\/\/world","age":"22","like":"i 222 no"}}]}'],
        ];
    }


    /**
     * @return array
     */
    public function getData()
    {
        return [
            [
                'id' => '1',
                'name' => 'jianbin',
                'jgdaima' => 'WBERBKJKJEWR',
                'date' => '1998',
                'adresss' => 'ggz',
                'email' => 'tangtang@gmail.org',
            ],
            [
                'id' => '2',
                'name' => 'jimb55',
                'jgdaima' => 'FHEWIH3274WENR234NE',
                'date' => '1994',
                'adresss' => 'bbf',
                'email' => 'Jimb@gmail.org',
                'myinfo' => [
                    'name' => 'jimb55',
                    'githubPage' => 'github://jimb55',
                    'age' => '22',
                    'like' => 'i down no',
                    'car'  => [
                        'id' => 123,
                        'name'  => "this is a car",
                        'yic' => [
                            'name' => 'de'
                        ]
                    ]
                ]
            ],
            [
                'id' => '3',
                'name' => 'tt',
                'jgdaima' => 'FHEWIH3274WENR234NE',
                'date' => '1994',
                'adresss' => 'ddw',
                'email' => 'www@gmail.org',
                'myinfo' => [
                    'name' => 'jjjj',
                    'githubPage' => 'hello://world',
                    'age' => '22',
                    'like' => 'i 222 no'
                ]
            ]
        ];
    }

}
