<?php
namespace Jimb\RestFilter\Test;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-05 at 09:01:21.
 */
class CommonTransformerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CommonTransformer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new CommonTransformer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Jimb\RestFilter\CommonTransformer::requiteFilter
     * @todo   Implement testRequiteFilter().
     */
    public function testRequiteFilter()
    {
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );

        $this -> equalTo(1,1);
    }
//
//    /**
//     * @covers Jimb\RestFilter\CommonTransformer::transform
//     * @todo   Implement testTransform().
//     */
//    public function testTransform()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Jimb\RestFilter\CommonTransformer::getTransformArr
//     * @todo   Implement testGetTransformArr().
//     */
//    public function testGetTransformArr()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Jimb\RestFilter\CommonTransformer::getFiled
//     * @todo   Implement testGetFiled().
//     */
//    public function testGetFiled()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Jimb\RestFilter\CommonTransformer::setFiled
//     * @todo   Implement testSetFiled().
//     */
//    public function testSetFiled()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Jimb\RestFilter\CommonTransformer::getFiledName
//     * @todo   Implement testGetFiledName().
//     */
//    public function testGetFiledName()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Jimb\RestFilter\CommonTransformer::setFiledName
//     * @todo   Implement testSetFiledName().
//     */
//    public function testSetFiledName()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
}


