<?php
namespace Jimb\RestFilter\Test;

use Jimb\RestFilter\CommonTransformer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-07 at 08:03:47.
 */
class CommonTransformerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var CommonTransformer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CommonTransformer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     *
     * @covers       Jimb\RestFilter\CommonTransformer::requiteFilter
     * @todo   Implement testRequiteFilter().
     */
    public function testRequiteFilterNotPar()
    {
        //测试无值的
        unset($_REQUEST[$this->object->getFiledName()]);
        $this->assertEquals($this->object->RequiteFilter(), false);

    }

    /**
     *
     * @dataProvider addRequiteFilterData
     * @covers       Jimb\RestFilter\CommonTransformer::requiteFilter
     * @todo   Implement testRequiteFilter().
     */
    public function testRequiteFilter($inserPar, $eq = "")
    {
        //测试有值的
        $_REQUEST[$this->object->getFiledName()] = $inserPar;
        $this->assertEquals($this->object->RequiteFilter(), $eq);

    }

    /**
     * @return array
     */
    public function addRequiteFilterData()
    {
        return [
            '< id,name,myinfo.car >' => ['id,name,myinfo.car', ['id' => '0', 'name' => '1', 'myinfo.car' => '2',]],
            '< id >' => ['id', ['id' => '0',]],
            '< 字段值为空 >' => ['', false],
        ];
    }

    /**
     *
     * @dataProvider addGetTransformArrData
     * @covers       Jimb\RestFilter\CommonTransformer::getTransformArr
     * @todo   Implement testGetTransformArr().
     */
    public function testGetTransformArr($inserPar, $eq = "")
    {

        // 新建一个全局管理类
        // 总体测试
        $_REQUEST[$this->object->getFiledName()] = $inserPar;

        $fractal = new \League\Fractal\Manager();
        $resource = new \League\Fractal\Resource\Collection($this->getData(),$this->object);

        $this->assertEquals($fractal->createData($resource)->toJson(), $eq);
    }


    /**
     * @return array
     */
    public function addGetTransformArrData()
    {
        $d1 = '{"data":[{"id":"1","name":"jianbin","myinfo":{"name":"kankanJ","car":{"id":123,"name":"car","yic":{"name":"hhhhcao"}}}},{"id":"2","name":"jimb55","myinfo":{"name":"MWIJD","car":{"id":121,"name":"bus","yic":{"name":"bilibili"}}}}]}';
        $d2 = '{"data":[{"myinfo":{"name":"kankanJ","car":{"id":123,"name":"car","yic":{"name":"hhhhcao"}}},"id":"1","name":"jianbin"},{"myinfo":{"name":"MWIJD","car":{"id":121,"name":"bus","yic":{"name":"bilibili"}}},"id":"2","name":"jimb55"}]}';
        //'<  >' => ['', ''],
        return [
            '< 空 >' => ['', '{"data":[{"id":"1","name":"jianbin","myinfo":{"name":"kankanJ","car":{"id":123,"name":"car","yic":{"name":"hhhhcao"}}}},{"id":"2","name":"jimb55","myinfo":{"name":"MWIJD","car":{"id":121,"name":"bus","yic":{"name":"bilibili"}}}}]}'],
            '< id >' => ['id', '{"data":[{"id":"1"},{"id":"2"}]}'],
            '< id,name >' => ['id,name', '{"data":[{"id":"1","name":"jianbin"},{"id":"2","name":"jimb55"}]}'],
            '< myinfo,id,name >' => ['myinfo,id,name', $d1],
            '< id,name,myinfo >' => ['id,name,myinfo', $d1],
            '< myinfo.name,myinfo.car,id,name,myinfo.car >' => ['myinfo.name,myinfo.car,id,name,myinfo.car',$d2],
            '< id,name,myinfo.car >' => ['myinfo.name,myinfo.car,id,name,myinfo.car',$d2],
            '< myinfo.name,myinfo.car.id,myinfo.car.yic >' => ['myinfo.name,myinfo.car.id,myinfo.car.yic', '{"data":[{"myinfo":{"name":"kankanJ","car":{"id":123,"yic":{"name":"hhhhcao"}}}},{"myinfo":{"name":"MWIJD","car":{"id":121,"yic":{"name":"bilibili"}}}}]}'],
            '< myinfo.name,myinfo.car.id,myinfo.car.yic,, >' => ['myinfo.name,myinfo.car.id,myinfo.car.yic,,', '{"data":[{"myinfo":{"name":"kankanJ","car":{"id":123,"yic":{"name":"hhhhcao"}}},"":""},{"myinfo":{"name":"MWIJD","car":{"id":121,"yic":{"name":"bilibili"}}},"":""}]}'],
            '< id,noval,myinfo.name,myinfo.car.id,myinfo.car.yic.noval >' => ['id,noval,myinfo.name,myinfo.car.id,myinfo.car.yic.noval', '{"data":[{"id":"1","noval":"","myinfo":{"name":"kankanJ","car":{"id":123,"yic":{"noval":""}}}},{"id":"2","noval":"","myinfo":{"name":"MWIJD","car":{"id":121,"yic":{"noval":""}}}}]}']
        ];
    }


    /**
     * 数据
     *
     * @return array
     */
    public function getData()
    {
        return [
            [
                'id' => '1',
                'name' => 'jianbin',
                'myinfo' => [
                    'name' => 'kankanJ',
                    'car'  => [
                        'id' => 123,
                        'name'  => "car",
                        'yic' => [
                            'name' => 'hhhhcao'
                        ]
                    ]
                ]
            ],
            [
                'id' => '2',
                'name' => 'jimb55',
                'myinfo' => [
                    'name' => 'MWIJD',
                    'car'  => [
                        'id' => 121,
                        'name'  => "bus",
                        'yic' => [
                            'name' => 'bilibili'
                        ]
                    ]
                ]
            ]
        ];
    }

}
//id,name,myinfo.car.name,myinfo.car.id
